sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t btfjulio/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true btfjulio/docker-react npm run test 